#!/usr/bin/env python3
"""
Derive pm/kpi-sla-thresholds.yaml from a JSON export of PmDataEnrichedResponse[].

Usage:
  python3 calibrate_pm_sla_yaml.py path/to/nodes.json > ../src/main/resources/pm/kpi-sla-thresholds.yaml

Bands (calibration envelope + headroom for live traffic):
  warn_high = max_obs * 1.06
  crit_high = max_obs * 1.15
  warn_low  = max(min_obs * 0.92, 0) if min_obs >= 0 else min_obs * 1.08
  crit_low  = max(min_obs * 0.85, 0) if min_obs >= 0 else min_obs * 1.15

Near-zero KPIs (max < 1e-3): use absolute warn/crit high instead.
"""
from __future__ import annotations

import json
import math
import sys
from collections import defaultdict
from pathlib import Path


def collect_values(nodes: list) -> dict[str, list[float]]:
    by: dict[str, list[float]] = defaultdict(list)
    for node in nodes:
        for row in node.get("data") or []:
            kpis = row.get("kpis") or {}
            for k, v in kpis.items():
                if v is not None and isinstance(v, (int, float)) and math.isfinite(float(v)):
                    by[str(k)].append(float(v))
        static = node.get("staticValues") or {}
        for k, v in static.items():
            if v is not None and isinstance(v, (int, float)) and math.isfinite(float(v)):
                by[str(k)].append(float(v))
    return by


def band_for(mn: float, mx: float) -> dict | None:
    if mn > mx:
        mn, mx = mx, mn
    if not math.isfinite(mn) or not math.isfinite(mx):
        return None
    # Constant zero — skip (no meaningful SLA band)
    if mn == 0 and mx == 0:
        return None

    # Tiny absolute scale (error-like counters)
    if mx < 1e-3:
        return {
            "warn-high": round(mx * 50, 10),
            "crit-high": round(mx * 200, 10),
        }

    warn_high = mx * 1.06
    crit_high = mx * 1.15
    out = {
        "warn-high": round(warn_high, 6 if abs(warn_high) < 1e6 else 3),
        "crit-high": round(crit_high, 6 if abs(crit_high) < 1e6 else 3),
    }
    if mn >= 0:
        out["warn-low"] = round(max(mn * 0.92, 0), 6 if mn * 0.92 < 1e6 else 3)
        out["crit-low"] = round(max(mn * 0.85, 0), 6 if mn * 0.85 < 1e6 else 3)
    else:
        out["warn-low"] = round(mn * 1.08, 6)
        out["crit-low"] = round(mn * 1.15, 6)
    return out


def emit_yaml(by_code: dict[str, dict]) -> str:
    lines = [
        "# PM KPI SLA bands — generated by scripts/calibrate_pm_sla_yaml.py",
        "# Re-run when calibration JSON changes. Live values outside these bands raise THRESHOLD_* anomalies.",
        "",
        "pm:",
        "  sla-thresholds:",
        "    version: 1",
        "    kpis:",
    ]
    for code in sorted(by_code.keys(), key=lambda x: (len(x), x)):
        lines.append(f'      "{code}":')
        b = by_code[code]
        for k in ("warn-high", "crit-high", "warn-low", "crit-low"):
            if k in b:
                lines.append(f"        {k}: {b[k]}")
    lines.append("")
    return "\n".join(lines)


# Min/max aggregated from customer sample export (Jan 2025, JUNIPER TRANSPORT routers).
# Regenerate from full JSON via: python3 calibrate_pm_sla_yaml.py your_export.json
_EMBEDDED_MIN_MAX: dict[str, tuple[float, float]] = {
    "0005": (313.33, 2254.37),
    "0006": (313.33, 2254.37),
    "0007": (313.33, 2254.37),
    "0008": (6.2e-7, 6.65e-4),
    "0009": (313.33, 2254.37),
    "0010": (132.59, 2383.48),
    "0131": (340.67, 2104.79),
    "0133": (340.67, 2104.79),
    "1045": (8.7, 203_490.02),
    "1046": (704.74, 27_927_637.2),
    "1047": (0.6427, 395.70),
    "1048": (1.689e8, 2.499e9),
    "1049": (138.25, 2104.97),
    "1050": (6.2e-7, 8.3e-6),
    "1051": (1.0, 1.711e9),
    "1054": (42.03, 7_559_474.77),
    "1055": (0.0874, 22_274.65),
    "1056": (0.087, 7_840_951.17),
    "1057": (3.481e8, 2.3638e9),
    "1059": (1.1157e8, 2.024e9),
    "1061": (1.684e9, 4.294967295e9),
    "1066": (313.33, 2254.37),
    "1133": (132.59, 2383.48),
}


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: calibrate_pm_sla_yaml.py <nodes.json>|embedded", file=sys.stderr)
        return 1
    arg = sys.argv[1]
    if arg == "embedded":
        bands = {}
        for code, (mn, mx) in _EMBEDDED_MIN_MAX.items():
            b = band_for(mn, mx)
            if b:
                bands[code] = b
        sys.stdout.write(emit_yaml(bands))
        return 0
    path = Path(arg)
    nodes = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(nodes, list):
        nodes = [nodes]
    vals = collect_values(nodes)
    bands = {}
    for code, vs in vals.items():
        b = band_for(min(vs), max(vs))
        if b:
            bands[code] = b
    sys.stdout.write(emit_yaml(bands))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
