package org.springaicommunity.nova.pm.service;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.DoubleSummaryStatistics;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springaicommunity.nova.pm.analytics.KpiSlaBand;
import org.springaicommunity.nova.pm.dto.PmDataCompactResponse.DataEntry;
import org.springaicommunity.nova.pm.dto.PmDataEnrichedResponse;
import org.springframework.stereotype.Service;

/**
 * Derives {@link KpiSlaBand} per KPI code from enriched PM samples (same rules as
 * {@code scripts/calibrate_pm_sla_yaml.py}) and formats {@code pm/kpi-sla-thresholds.yaml}.
 */
@Service
public class PmSlaThresholdCalibrationService {

    private static final double TINY_SCALE_MAX = 1e-3;

    /**
     * Collects min/max per KPI across all time points and static values for every node in the list.
     */
    public Map<String, KpiSlaBand> deriveBands(List<PmDataEnrichedResponse> nodes) {
        Map<String, DoubleSummaryStatistics> stats = new LinkedHashMap<>();
        for (PmDataEnrichedResponse node : nodes) {
            accumulate(node, stats);
        }
        Map<String, KpiSlaBand> bands = new LinkedHashMap<>();
        for (String code : stats.keySet().stream().sorted(this::compareKpiCode).toList()) {
            DoubleSummaryStatistics s = stats.get(code);
            if (s.getCount() == 0) {
                continue;
            }
            KpiSlaBand band = bandFor(s.getMin(), s.getMax());
            if (band != null) {
                bands.put(code, band);
            }
        }
        return bands;
    }

    public String formatYaml(Map<String, KpiSlaBand> bands) {
        List<String> lines = new ArrayList<>();
        lines.add("# PM KPI SLA bands — generated by POST/GET /pm/data/sla-thresholds/yaml from live PM samples.");
        lines.add("# Re-calibrate when traffic baseline shifts.");
        lines.add("");
        lines.add("pm:");
        lines.add("  sla-thresholds:");
        lines.add("    version: 1");
        lines.add("    kpis:");
        for (String code : bands.keySet().stream().sorted(this::compareKpiCode).toList()) {
            KpiSlaBand b = bands.get(code);
            lines.add("      \"" + code + "\":");
            if (b.getWarnHigh() != null) {
                lines.add("        warn-high: " + yamlDouble(b.getWarnHigh()));
            }
            if (b.getCritHigh() != null) {
                lines.add("        crit-high: " + yamlDouble(b.getCritHigh()));
            }
            if (b.getWarnLow() != null) {
                lines.add("        warn-low: " + yamlDouble(b.getWarnLow()));
            }
            if (b.getCritLow() != null) {
                lines.add("        crit-low: " + yamlDouble(b.getCritLow()));
            }
        }
        lines.add("");
        return String.join("\n", lines);
    }

    private void accumulate(PmDataEnrichedResponse node, Map<String, DoubleSummaryStatistics> stats) {
        if (node.getData() != null) {
            for (DataEntry row : node.getData()) {
                if (row.getKpis() == null) {
                    continue;
                }
                for (Map.Entry<String, Double> e : row.getKpis().entrySet()) {
                    addSample(stats, e.getKey(), e.getValue());
                }
            }
        }
        if (node.getStaticValues() != null) {
            for (Map.Entry<String, Double> e : node.getStaticValues().entrySet()) {
                addSample(stats, e.getKey(), e.getValue());
            }
        }
    }

    private static void addSample(Map<String, DoubleSummaryStatistics> stats, String code, Double v) {
        if (v == null || !Double.isFinite(v)) {
            return;
        }
        stats.computeIfAbsent(code, c -> new DoubleSummaryStatistics()).accept(v);
    }

    /**
     * Same semantics as {@code band_for} in {@code calibrate_pm_sla_yaml.py}.
     */
    KpiSlaBand bandFor(double mn, double mx) {
        if (Double.isNaN(mn) || Double.isNaN(mx) || !Double.isFinite(mn) || !Double.isFinite(mx)) {
            return null;
        }
        if (mn > mx) {
            double t = mn;
            mn = mx;
            mx = t;
        }
        if (mn == 0 && mx == 0) {
            return null;
        }
        if (mx < TINY_SCALE_MAX) {
            return new KpiSlaBand(
                    roundTiny(mx * 50),
                    roundTiny(mx * 200),
                    null,
                    null);
        }
        double warnHigh = roundYaml(mx * 1.06);
        double critHigh = roundYaml(mx * 1.15);
        if (mn >= 0) {
            return new KpiSlaBand(
                    warnHigh,
                    critHigh,
                    roundYaml(Math.max(mn * 0.92, 0)),
                    roundYaml(Math.max(mn * 0.85, 0)));
        }
        return new KpiSlaBand(
                warnHigh,
                critHigh,
                roundYaml(mn * 1.08),
                roundYaml(mn * 1.15));
    }

    private static double roundTiny(double v) {
        return Math.round(v * 1e10) / 1e10;
    }

    private static double roundYaml(double v) {
        double av = Math.abs(v);
        if (av < 1_000_000) {
            return Math.round(v * 1_000_000.0) / 1_000_000.0;
        }
        return Math.round(v * 1_000.0) / 1_000.0;
    }

    private static String yamlDouble(double v) {
        if (Double.isNaN(v) || Double.isInfinite(v)) {
            return "0";
        }
        return BigDecimal.valueOf(v).stripTrailingZeros().toPlainString();
    }

    /** Numeric-aware sort for KPI codes like 0005 vs 1046. */
    private int compareKpiCode(String a, String b) {
        try {
            int ia = Integer.parseInt(a);
            int ib = Integer.parseInt(b);
            return Integer.compare(ia, ib);
        } catch (NumberFormatException e) {
            return a.compareTo(b);
        }
    }

    public List<String> summarizeNodes(List<PmDataEnrichedResponse> nodes) {
        return nodes.stream()
                .map(n -> n.getSummary() != null && n.getSummary().getNode() != null
                        ? n.getSummary().getNode()
                        : "?")
                .collect(Collectors.toList());
    }
}
